### PR TITLE
created chainspec for public testnet

### PR DESCRIPTION
**Pull request by gleb-urvanov**

### CODE REVIEW

**Comment by omaksi** [comment]
1. What is the intended usage of this chainspec?
2. Also I'm a bit confused about the hardcoded localhost bootnode, what is the reason for it?

**Comment by gleb-urvanov** [comment]
> What is the intended usage of this chainspec?  
It is for the public testnet, we should use it in the next testnet iteration. It replaces the testing keys we are currently using with private keys for our validator and relayer

> Also I'm a bit confused about the hardcoded localhost bootnode, what is the reason for it?  
My bad, should be removed

**Comment by omaksi** [comment]
1. Which keys are being used now?
2. It seems the babe key is not //Alice but grandpa key is //Alice

**Comment by gleb-urvanov** [comment]
> Which keys are being used now?

provided using secure channel
> It seems the babe key is not //Alice but grandpa key is //Alice

nice catch, I forgot about different scheme. Replaced.

**Pull request merged**
